package main

import (
	"os"
	"path/filepath"
	"testing"
)

func sampleProof() *Proof {
	return &Proof{Repos: 13, Lines: map[string]int{"Go": 130816, "Shell": 84260, "TypeScript": 2266, "JavaScript": 2409},
		GoCode: 56157, GoTest: 74659, GoTests: 1537, ReposWithCI: 13, Workflows: 36, ActionUses: 158, ActionsPinned: 118}
}

// TestMeasureRules checks each counting rule on a tiny fake checkout.
func TestMeasureRules(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{
		"main.go":                  "package main\n\nfunc main() {}\n",
		"main_test.go":             "package main\n\nfunc TestA(t *testing.T) {}\nfunc BenchmarkB(b *testing.B) {}\nfunc helper() {}\n",
		"gen.pb.go":                "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main\nvar x = 1\n",
		"vendor/dep/dep.go":        "package dep\nvar y = 2\n",
		"run.sh":                   "#!/bin/sh\nset -eu\necho hi\n",
		"loose.sh":                 "#!/bin/sh\necho hi\n",
		".github/workflows/ci.yml": "jobs:\n  a:\n    steps:\n      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7\n      - uses: actions/setup-go@v5\n      - uses: ./local\n",
		"README.md":                "# not code\n",
	}
	for name, body := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	p := &Proof{Lines: map[string]int{}}
	if err := p.measure(root); err != nil {
		t.Fatal(err)
	}
	checks := []struct {
		name      string
		got, want int
	}{
		{"Go code lines (generated and vendor excluded)", p.GoCode, 2},
		{"Go test lines", p.GoTest, 4},
		{"Go test functions", p.GoTests, 2},
		{"shell scripts", p.ShellScripts, 2},
		{"strict shell scripts", p.ShellStrict, 1},
		{"repos with CI", p.ReposWithCI, 1},
		{"action uses (local excluded)", p.ActionUses, 2},
		{"actions pinned", p.ActionsPinned, 1},
	}
	for _, c := range checks {
		if c.got != c.want {
			t.Errorf("%s = %d, want %d", c.name, c.got, c.want)
		}
	}
}

func TestKilo(t *testing.T) {
	for in, want := range map[int]string{999: "999", 1234: "1.2k", 56157: "56k"} {
		if got := kilo(in); got != want {
			t.Errorf("kilo(%d) = %q, want %q", in, got, want)
		}
	}
}
