package main

import (
	"fmt"
	"strings"
)

// assets lists the SVGs rendered per theme, in page order.
var assets = []struct{ file, alt string }{
	{"header", "kodflow"},
	{"card", "At a glance"},
	{"timeline", "Stack over time"},
}

// picture emits a <picture> that follows the visitor's colour scheme. base
// is where the SVGs live: the output branch on GitHub, a folder for previews.
func picture(base, name, alt string) string {
	return fmt.Sprintf(`<picture>
  <source media="(prefers-color-scheme: dark)" srcset="%[1]s/%[2]s-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="%[1]s/%[2]s-light.svg">
  <img alt="%[3]s" src="%[1]s/%[2]s-dark.svg" width="100%%">
</picture>`, base, name, esc(alt))
}

// renderREADME builds the profile README. It is generated rather than hand
// written so the project list and the images can never drift from profile.json.
func renderREADME(p *Profile, base string) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by cmd/profile from profile.json: edit those, not this file. -->\n\n")
	b.WriteString(picture(base, "header", "kodflow") + "\n\n")
	b.WriteString(picture(base, "card", "At a glance") + "\n\n")
	b.WriteString("### Selected work\n\n| Project | What it does |\n|---|---|\n")
	for _, pr := range p.Projects {
		fmt.Fprintf(&b, "| [**%s**](https://github.com/%s/%s) | %s |\n", pr.Repo, p.Login, pr.Repo, strings.ReplaceAll(pr.What, "|", `\|`))
	}
	b.WriteString("\n" + picture(base, "timeline", "Stack over time") + "\n\n")
	b.WriteString("<sub>Rendered every day by a small Go program in this repository, from the public GitHub API only. " +
		"No third-party stat service, no tracking pixel.</sub>\n")
	return b.String()
}
